controllers/CashboxController.php
<?php

namespace app\controllers;

use app\models\Clients;
use app\models\Money;
use yii\web\Controller;
use app\models\Cashbox;

use Yii;
class CashboxController extends Controller{

    public function actionIndex(){

        $cashbox_model = new Cashbox();
        $money_model = new Money();

        $clients = Clients::find()->asArray()->with('money')->all();
        $money = Money::find()->asArray()->with('clients')->all();
        $cashbox = Cashbox::find()->select('begin_saldo')->asArray()->all();

        if( $cashbox_model->load(Yii::$app->request->post()) && $money_model->load(Yii::$app->request->post())){

            if($cashbox_model->save() && $money_model->save()){

                $money_model->client_id = Yii::$app->request->post()->client_id;
                $money_model->payment_sum = Yii::$app->request->post()->payment_sum;
                Yii::$app->session->setFlash('success', 'Добавлено');
                return $this->redirect(Yii::$app->request->referrer);
            } else {
                Yii::$app->session->setFlash('error', 'Ошибка при добавление');
            }
        }

        return $this->render('index', compact('cashbox_model', 'money_model', 'clients', 'money', 'cashbox'));
    }

    public function actionEdit(){


        $id = Yii::$app->request->post('id');
        $money = Money::findOne($id);

        $money->payment_sum = Yii::$app->request->post('payment_sum');
        $money->save();

    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Cashbox;
use app\models\Clients;
use Yii;
use app\models\Signup;
use app\models\Login;
use yii\web\Controller;
use app\models\Money;


class SiteController extends Controller{

    public function actionIndex(){
        $cashbox = Cashbox::find()->asArray()->with('user')->all();
        $money = Money::find()->asArray()->with('clients')->all();
        $clients = Clients::find()->asArray()->with('money')->all();
        $login_model = new Login();

        $Allsum = 0;
        $sum = 0;
        foreach ($cashbox as $cash){
            $Allsum += $cash['begin_saldo'];
        }
        foreach ($money as $mon) {
            $sum += $mon['payment_sum'];
        }


        if(Yii::$app->request->post('Login')){
            $login_model->attributes = Yii::$app->request->post('Login');

            if($login_model->validate()){
                Yii::$app->user->login($login_model->getUser());
                return $this->goHome();
            }
        }

        return $this->render('index', compact('cashbox', 'login_model', 'clients' , 'Allsum', 'sum'));
    }

    public function actionLogout(){
        if(!Yii::$app->user->isGuest){
            Yii::$app->user->logout();
            return $this->goHome();
        }
    }

    public function actionSignup(){

        $model = new Signup();
        if(isset($_POST['Signup'])){
            $model->attributes = Yii::$app->request->post('Signup');

            if($model->validate() && $model->signup()){
                return $this->goHome();
            }
        }

        return $this->render('signup', compact('model'));
    }



}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;

?>

<?php if(!Yii::$app->user->isGuest): ?>

<div class="container">
    <a href="<?= \yii\helpers\Url::to(['cashbox/index']) ?>"><button class="btn btn-default">Добавить дневную касу</button></a>


<table class="table table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Дата</th>
            <th scope="col">Администратор</th>
            <th scope="col">Сума на начало</th>
            <th scope="col">Оборот</th>
            <th scope="col">Сумма на конец</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($cashbox as $val): ?>
            <?php $max = $val['begin_saldo'] + $sum ?>
        <tr>
            <th><?= $val['payment_day'] ?></th>
            <th><?= $val['user']['login'] ?></th>
            <th><?= $val['begin_saldo'] ?></th>
            <th><?= $Allsum - $val['begin_saldo'] ?></th>
            <th><?= $Allsum  ?></th>
        </tr>

        <?php endforeach; ?>
        </tbody>
    </table>
</table>

</div>

<?php endif; ?>
<?php if(Yii::$app->user->isGuest) : ?>
<h2>Вход</h2>
<p>Login: vadim</p>
<p>Password: 1111</p>
<p></p>
<?php $form =  ActiveForm::begin() ?>

<?= $form->field($login_model, 'login')->textInput(['autofocus' => true]) ?>
<?= $form->field($login_model, 'password')->input('password') ?>

<?= Html::submitButton('Вход', ['class' => 'btn btn-success']) ?>

<?php ActiveForm::end() ?>

<?php endif; ?>

views/site/new.php
<?php
/**
 * Created by PhpStorm.
 * User: vadim
 * Date: 23.11.2017
 * Time: 16:07
 */

views/site/signup.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;


?>
<h2>Регистрация</h2>

<?php $form =  ActiveForm::begin() ?>

<?= $form->field($model, 'login')->textInput(['autofocus' => true]) ?>
<?= $form->field($model, 'password')->input('password') ?>

<?= Html::submitButton('Регистрация', ['class' => 'btn btn-success']) ?>

<?php ActiveForm::end() ?>